# Conventional Commits: https://www.conventionalcommits.org/en/v1.0.0/

[commit]
default-ignores = true

[[commit.slots]]
name = "keywords"
kind = "word"
values = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "refactor",
  "revert",
  "style",
  "test",
]
required = true

[[commit.slots]]
name = "scope"
delimiters = ["(", ")"]

[[commit.slots]]
name = "modifiers"
kind = "symbols"
values = ["!"]

[[commit.slots]]
name = "separator"
kind = "symbol"
values = [":"]
required = true
