# Standard Commits: https://github.com/standard-commits/standard-commits

[commit]
default-ignores = true

[[commit.slots]]
name = "keywords"
kind = "word"
values = ["add", "rem", "ref", "fix", "undo", "release"]
required = true

[[commit.slots]]
name = "modifiers"
kind = "symbols"
values = ["?", "!", "!!"]

[[commit.slots]]
name = "scope"
delimiters = ["(", ")"]
values = ["exe", "lib", "test", "build", "doc", "ci", "cd"]

[[commit.slots]]
name = "reason"
delimiters = ["[", "]"]
values = [
  "int",
  "pre",
  "eff",
  "rel",
  "cmp",
  "mnt",
  "tmp",
  "exp",
  "sec",
  "upg",
  "ux",
  "pol",
  "sty",
]

[[commit.slots]]
name = "separator"
kind = "symbol"
values = [":"]
required = true
