# [unstable]
# codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1

[target."cfg(all())"]
rustflags = [
  "-Zunstable-options",
  "-Clink-self-contained=+linker",
  "-Clinker-features=+lld",
  "-Zshare-generics=y",
  "-Zthreads=0",
]
