[tools]
hk = "latest"
rust = "nightly"
"cargo:cargo-nextest" = "latest"

tombi = "latest"
yq = "latest"

actionlint = "latest"
shellcheck = "latest"

[env]
HK_MISE = 1

[hooks]
postinstall = "hk install --mise"

[tasks."test:rust"]
description = "Test the Rust project"
run = "cargo nextest run --workspace"
