// Generates presets/gitmoji.toml from the gitmoji catalogue, so the
// ~75 emoji and shortcodes are not hand-maintained in two spellings.
// Run with `bun scripts/gitmoji.ts`.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const source = "https://gitmoji.dev/api/gitmojis";
const target = new URL("../presets/gitmoji.toml", import.meta.url);

interface Gitmoji {
  emoji: string;
  code: string;
}

const response = await fetch(source);

if (!response.ok) {
  throw new Error(`${source}: ${response.status}`);
}

const { gitmojis } = (await response.json()) as { gitmojis: Gitmoji[] };
const emoji = gitmojis.map((gitmoji) => gitmoji.emoji);

// A delimited slot matches its contents against the set, so word chars
// and hyphens are fine; anything else (whitespace, a nested delimiter)
// has no slot that can hold it. Its emoji still stands.
const shortcodes = gitmojis
  .map((gitmoji) => gitmoji.code.slice(1, -1))
  .filter((code) => /^[\w-]+$/u.test(code));
const dropped = gitmojis.length - shortcodes.length;

const list = (values: string[]) =>
  `[\n${values.map((value) => `  ${JSON.stringify(value)},\n`).join("")}]`;

writeFileSync(
  fileURLToPath(target),
  `# Gitmoji: https://gitmoji.dev/specification
# Generated by scripts/gitmoji.ts from ${source}; ${dropped} shortcode(s)
# with a non-word character are dropped, their emoji kept.

[commit]
default-ignores = true

[[commit.slots]]
name = "intention"
required = true
gap = true

[[commit.slots.one-of]]
name = "emoji"
kind = "symbols"
values = ${list(emoji)}

[[commit.slots.one-of]]
name = "shortcode"
delimiters = [":", ":"]
values = ${list(shortcodes)}

[[commit.slots]]
name = "scope"
delimiters = ["(", ")"]

[[commit.slots]]
name = "separator"
kind = "symbol"
values = [":"]
`,
);

console.info(`wrote ${emoji.length} emoji, ${shortcodes.length} shortcodes`);
