name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: oven-sh/setup-bun@v2
      - run: bun ci
      - run: bun run check

  cov:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: |
            cargo-llvm-cov
            cargo-nextest
      - run: mkdir -p target/llvm-cov
      - run: cargo llvm-cov nextest --workspace --all-targets --all-features --locked --fail-under-regions 90 --codecov --output-path target/llvm-cov/codecov.json
      - if: github.ref_type != 'tag'
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          use_oidc: true
          report_type: coverage
          disable_search: true
          files: target/llvm-cov/codecov.json
      - if: github.ref_type != 'tag'
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          use_oidc: true
          report_type: test_results
          disable_search: true
          files: target/nextest/default/junit.xml
